"use strict";

module.exports = {
    INITIALIZE: 'INITIALIZE_APP',

    REQUEST_LOGIN_USER: 'REQUEST_LOGIN_USER',
    REQUEST_LOGIN_USER_SUCCESS: 'REQUEST_LOGIN_USER_SUCCESS',
    REQUEST_LOGIN_USER_ERROR: 'REQUEST_LOGIN_USER_ERROR',

    REQUEST_LOGOUT_USER: 'REQUEST_LOGOUT_USER',

    CREATE_AUTHOR: 'CREATE_AUTHOR',
    UPDATE_AUTHOR: 'UPDATE_AUTHOR',
    DELETE_AUTHOR: 'DELETE_AUTHOR'

};
