"use strict";

module.exports = {
    INITIALIZE: 'INITIALIZE_APP',

    REQUEST_LOGIN_USER: 'REQUEST_LOGIN_USER',
    REQUEST_LOGIN_USER_SUCCESS: 'REQUEST_LOGIN_USER_SUCCESS',
    REQUEST_LOGIN_USER_ERROR: 'REQUEST_LOGIN_USER_ERROR',

    REQUEST_LOGOUT_USER: 'REQUEST_LOGOUT_USER',

    REQUEST_START_WORK: 'REQUEST_START_WORK',
    REQUEST_END_WORK: 'REQUEST_END_WORK',
    REQUEST_BACKEND_ERROR: 'REQUEST_BACKEND_ERROR'

};
